-- CreateTable
CREATE TABLE `score` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(64) NOT NULL,
    `SCORE` INTEGER NOT NULL,
    `TIMESTAMP` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `MAIL`(`NAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
